- name: Install often used packages
  sudo: yes
  apt: pkg={{ item.pkg }} state=latest update_cache=yes
  with_items:
    - { pkg: 'git'}
    - { pkg: 'build-essential'}
    - { pkg: 'pkg-config'}
    - { pkg: 'python2.7-dev'}
    - { pkg: 'python-pip'}
    - { pkg: 'python-software-properties'}
    - { pkg: 'python-pycurl'}
  tags:
    - common

- name: Pip | Install fundamental Python modules
  sudo: yes
  pip: name={{ item.pkg }} state=latest
  with_items:
    - { pkg: 'pip'}
    - { pkg: 'virtualenv'}
    - { pkg: 'virtualenvwrapper'}
    - { pkg: 'ipython'}
    - { pkg: 'glances'}
  tags:
    - common
    - python

- name: Create folders for Virtual Environments
  file:
    path=/home/{{ user }}/.virtualenvs
    state=directory
    owner={{ user }}
    group={{ user }}
    mode=0755
  tags:
    - common
    - python

- name: Add VirtualEnvWrapper info to .bashrc
  lineinfile:
    dest=/home/{{ user }}/.bashrc
    line={{ item.line }}
  with_items:
      - { line: 'export WORKON_HOME=/home/{{ user }}/.virtualenvs'}
      - { line: 'export PROJECT_HOME=/home/{{ user }}/Dev'}
      - { line: 'source /usr/local/bin/virtualenvwrapper.sh'}
  tags:
    - common
    - python


